### ISSUE TITLE
New  Multi purpose PIC rs-485 remote

### ISSUE THREAD

**Issue by danjperron** [danjperron/NoContactWaterDetect#2]
I got a small bug on the RS-485 shematic. it will fix it tonight.

R3 and R4 are on the wrong sink/source  . 

B.T.W.  I create an other PIC remote system, with modbus protocol, which you could change the pin mode, (Analog 10 bits, digital in/out, R/C servo , DHT11,DHT22, DS18B20 temperature readers and  pulse counter,

https://github.com/danjperron/PicMultiPurpose.git

**Comment by rosvig** [comment]
Daniel i did different test, and checked the code, was wrongly connecting Rx and Tx, 
Now the step 4 is working, and now i will continue to test the complet circuit.
I will let you know how this test goes, thank you for your help.
